//----------------------------------------------------------------------------------
//! UMDUnwinding module definitions.
/*!
// \file    Unwinding.script
// \author  Hannes
// \date    2017-06-20
*/
//----------------------------------------------------------------------------------


Window {
  Vertical {
    margin = 3
    Field Y-Size {
    }
    Field Z-Size {
    }
    Field Method {
    }
    Field Compute {
    }
  }
}