//----------------------------------------------------------------------------------
//! UMDAortaUnwinding module definitions.
/*!
// \file    AortaUnwinding.script
// \author  Hannes
// \date    2017-05-09
*/
//----------------------------------------------------------------------------------


Window {
  Vertical {
    margin = 3
    Field Y-Size {
    }
    Field Z-Size {
    }
    Field Method {
    }
    Field Compute {
    }
  }
}